FROM oven/bun:1.3

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY . .
RUN bun install --frozen-lockfile
RUN bun run build

EXPOSE 3000
CMD ["bun", "run", "--filter", "@tixkit/checkout", "start"]
