apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tixkit.fullname" . }}-api
  labels:
    {{- include "tixkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  minReadySeconds: {{ .Values.availability.rollingUpdate.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.availability.rollingUpdate.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.availability.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.availability.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      {{- include "tixkit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "tixkit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- include "tixkit.podSecurity" (dict "root" . "component" "api") | nindent 6 }}
      containers:
        - name: api
          image: {{ include "tixkit.image" (dict "Values" .Values "image" .Values.api.image "digest" .Values.api.imageDigest) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
          env:
            - name: PORT
              value: {{ .Values.api.port | quote }}
            - name: UPLOAD_MALWARE_SCANNER
              value: {{ .Values.uploads.malwareScanner.mode | quote }}
            - name: CLAMAV_HOST
              value: {{ .Values.uploads.malwareScanner.host | quote }}
            - name: CLAMAV_PORT
              value: {{ .Values.uploads.malwareScanner.port | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "tixkit.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.name }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tixkit.fullname" . }}-api
  labels:
    {{- include "tixkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "tixkit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
