{{- if eq .Values.secrets.mode "external" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tixkit.fullname" . }}
  labels:
    {{- include "tixkit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ required "secrets.externalSecret.secretStoreName is required" .Values.secrets.externalSecret.secretStoreName }}
    kind: {{ .Values.secrets.externalSecret.secretStoreKind }}
  target:
    name: {{ required "secrets.name is required" .Values.secrets.name }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.secrets.externalSecret.data | nindent 4 }}
{{- end }}
