{{- if and .Values.migrations.enabled (eq .Values.migrations.strategy "hook") (eq .Values.secrets.mode "create") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-migration
  labels:
    {{- include "tixkit.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  DATABASE_URL_MYSQL: {{ .Values.secrets.databaseUrlMysql | quote }}
{{- end }}
