apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tixkit.fullname" . }}-worker
  labels:
    {{- include "tixkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "tixkit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "tixkit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "tixkit.image" (dict "Values" .Values "image" .Values.worker.image "digest" .Values.worker.imageDigest) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "tixkit.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.name }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
