services:
  - type: web
    name: tixkit-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: postgres
      - key: REDIS_URL
        fromService:
          type: redis
          name: tixkit-redis
          property: connectionString
      - key: PORT
        value: 4000
      - key: TRUST_PROXY
        value: 1
      - key: CORS_ALLOWED_ORIGINS
        value: https://checkout.example.com,https://admin.example.com
      - key: TEMPORAL_ADDRESS
        sync: false
      - key: TEMPORAL_NAMESPACE
        sync: false
      - key: TEMPORAL_TASK_QUEUE
        value: tixkit-production
    plan: starter

  - type: worker
    name: tixkit-worker
    env: docker
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: postgres
      - key: REDIS_URL
        fromService:
          type: redis
          name: tixkit-redis
          property: connectionString
      - key: TEMPORAL_ADDRESS
        sync: false
      - key: TEMPORAL_NAMESPACE
        sync: false
      - key: TEMPORAL_TASK_QUEUE
        value: tixkit-production
    plan: starter

  - type: web
    name: tixkit-checkout
    env: docker
    dockerfilePath: ./Dockerfile.checkout
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_TIXKIT_API_BASE_URL
        value: https://tixkit-api.onrender.com/v1
    plan: starter

  - type: web
    name: tixkit-admin
    env: docker
    dockerfilePath: ./Dockerfile.admin
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: NEXT_PUBLIC_ADMIN_API_BASE_URL
        value: https://tixkit-api.onrender.com
    plan: starter

databases:
  - name: postgres
    plan: starter

  - name: tixkit-redis
    type: redis
    plan: starter
