export {
  EVENT_PAGE_SCHEMA_VERSION as EVENT_PAGE_DOCUMENT_V2_SCHEMA_VERSION,
  EVENT_PAGE_LEGACY_COMMERCE_BLOCK_TYPES as EVENT_PAGE_PUCK_CHECKOUT_CHROME_COMPONENT_TYPES,
  PUCK_EVENT_PAGE_PROVIDER as EVENT_PAGE_PUCK_PROVIDER,
  createDefaultEventPageData,
  createDefaultEventPageDocument,
  createDefaultEventPageSettings,
  isEventPageDocumentV2,
  migrateEventPageDocumentToV2,
  migrateLegacyEventPageBlocksToPuckData,
  migrateLegacyEventPageDocumentToPuck,
  normalizeEventPageDocumentV2,
  normalizeOrMigrateEventPageDocumentV2,
  normalizePublicEventPagePayloadV2,
  resolveEventPageDocumentV2Discovery,
  validateEventPageDocument,
  validateEventPageDocumentV2,
  validateEventPagePuckData,
} from './index.js';

export type {
  EventPageDiscoveryCard,
  EventPageDiscoveryCardV2,
  EventPageDiscoveryMetadata,
  EventPageDiscoveryMetadataV2,
  EventPageDocument,
  EventPageDocumentV2,
  EventPagePublicDocumentMetadataV2,
  EventPagePublicVersionMetadataV2,
  EventPagePuckData,
  EventPagePuckRootData,
  EventPageRenderContext,
  EventPageRootProps,
  EventPageSettings,
  EventPageSettingsV2,
  EventPageValidationResultV2,
  PublicEventPagePayloadV2,
} from './index.js';
