/**
 * Centralized route constants for the admin dashboard.
 * Use these instead of hard-coded path strings so navigation stays consistent.
 */
export const routes = {
  root: '/',
  dashboard: '/dashboard',
  events: '/events',
  eventDetail: (eventId: string) => `/events/${eventId}`,
  eventTickets: (eventId: string) => `/events/${eventId}/tickets`,
  eventProducts: (eventId: string) => `/events/${eventId}/products`,
  eventCheckoutForm: (eventId: string) => `/events/${eventId}/checkout-form`,
  eventContentEventPage: (eventId: string) => `/events/${eventId}/content/event-page`,
  eventContentEmail: (eventId: string) => `/events/${eventId}/content/email`,
  eventContentSms: (eventId: string) => `/events/${eventId}/content/sms`,
  eventAttendees: (eventId: string) => `/events/${eventId}/attendees`,
  eventCheckIn: (eventId: string) => `/events/${eventId}/check-in`,
  eventMessages: (eventId: string) => `/events/${eventId}/messages`,
  eventReports: (eventId: string) => `/events/${eventId}/reports`,
  orders: '/orders',
  orderDetail: (orderId: string) => `/orders/${orderId}`,
  attendees: '/attendees',
  checkIn: '/check-in',
  messages: '/messages',
  reports: '/reports',
  developer: '/developer',
  developerApiKeys: '/developer/api-keys',
  developerWebhooks: '/developer/webhooks',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsWorkspace: '/settings/workspace',
  settingsOrganization: '/settings/organization',
  settingsAppearance: '/settings/appearance',
  settingsMembers: '/settings/members',
  settingsTeam: '/settings/team',
  settingsBilling: '/settings/billing',
  settingsPayments: '/settings/payments',
  settingsBranding: '/settings/branding',
  help: '/help',
  auditLog: '/audit-log',
  signIn: '/sign-in',
  signUp: '/sign-up',
} as const;

export type RouteKey = keyof typeof routes;
