export {
  EVENT_PAGE_PUCK_STYLES_CLASS,
  BrandFooterBlock,
  ButtonBlock,
  CheckoutCtaBlock,
  CustomEmbedBlock,
  DividerBlock,
  EventDetailsBlock,
  EventHeaderBlock,
  EventPageRender,
  EventPagePuckRender,
  EventPageRoot,
  EventPageRuntimeProvider,
  FAQBlock,
  MediaBlock,
  PublicEventPageSurface,
  ProductAddOnsBlock,
  ResaleTicketsBlock,
  RichTextBlock,
  ScheduleBlock,
  SocialLinksBlock,
  SpeakersBlock,
  SponsorsBlock,
  TicketsBlock,
  VenueBlock,
  createEventPagePuckConfig,
  createEventPageRenderStyle,
  eventPagePuckConfig,
  eventPagePuckIframeConfig,
  formatEventPageMoney,
  isEventPagePuckData,
  isEventPagePuckComponentType,
  resolveRenderData,
  ticketPriceLabel,
  useEventPageRuntime,
} from './index.js';

export type {
  EventPagePuckCategory,
  EventPagePuckComponentProps,
  EventPagePuckConfig,
  EventPagePuckCoreData,
  EventPagePuckConfigOptions,
  EventPageMediaChoice,
  EventPagePuckUploadImage,
  EventPageRenderProps,
  EventPageRuntime,
  PublicEventPageChrome,
  PublicEventPageFooterLink,
  PublicEventPageProduct,
  PublicEventPageResaleListing,
  PublicEventPageSurfaceProps,
  PublicEventPageTicket,
} from './index.js';

export {
  EVENT_PAGE_DOCUMENT_V2_SCHEMA_VERSION,
  EVENT_PAGE_PUCK_PROVIDER,
  createDefaultEventPageDocument,
  ensureEventPageChromeBlocks,
  isEventPageDocumentV2,
  normalizeEventPageDocumentV2,
  normalizePublicEventPagePayloadV2,
  validateEventPageDocumentV2,
} from '@tixkit/content-event-page/puck';

export type {
  EventPageDocumentV2,
  EventPagePuckData,
  EventPageSettingsV2,
  PublicEventPagePayloadV2,
} from '@tixkit/content-event-page/puck';
